package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DependenciaDeServicioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDependenciaDeServicioAllPropertiesEquals(DependenciaDeServicio expected, DependenciaDeServicio actual) {
        assertDependenciaDeServicioAutoGeneratedPropertiesEquals(expected, actual);
        assertDependenciaDeServicioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDependenciaDeServicioAllUpdatablePropertiesEquals(
        DependenciaDeServicio expected,
        DependenciaDeServicio actual
    ) {
        assertDependenciaDeServicioUpdatableFieldsEquals(expected, actual);
        assertDependenciaDeServicioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDependenciaDeServicioAutoGeneratedPropertiesEquals(
        DependenciaDeServicio expected,
        DependenciaDeServicio actual
    ) {
        assertThat(actual)
            .as("Verify DependenciaDeServicio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDependenciaDeServicioUpdatableFieldsEquals(DependenciaDeServicio expected, DependenciaDeServicio actual) {
        assertThat(actual)
            .as("Verify DependenciaDeServicio relevant properties")
            .satisfies(a -> assertThat(a.getPeso()).as("check peso").isEqualTo(expected.getPeso()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDependenciaDeServicioUpdatableRelationshipsEquals(
        DependenciaDeServicio expected,
        DependenciaDeServicio actual
    ) {
        assertThat(actual)
            .as("Verify DependenciaDeServicio relationships")
            .satisfies(a -> assertThat(a.getDependiente()).as("check dependiente").isEqualTo(expected.getDependiente()))
            .satisfies(a -> assertThat(a.getOrigen()).as("check origen").isEqualTo(expected.getOrigen()));
    }
}
