package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImpactoPropagadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpactoPropagadoAllPropertiesEquals(ImpactoPropagado expected, ImpactoPropagado actual) {
        assertImpactoPropagadoAutoGeneratedPropertiesEquals(expected, actual);
        assertImpactoPropagadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpactoPropagadoAllUpdatablePropertiesEquals(ImpactoPropagado expected, ImpactoPropagado actual) {
        assertImpactoPropagadoUpdatableFieldsEquals(expected, actual);
        assertImpactoPropagadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpactoPropagadoAutoGeneratedPropertiesEquals(ImpactoPropagado expected, ImpactoPropagado actual) {
        assertThat(actual)
            .as("Verify ImpactoPropagado auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpactoPropagadoUpdatableFieldsEquals(ImpactoPropagado expected, ImpactoPropagado actual) {
        assertThat(actual)
            .as("Verify ImpactoPropagado relevant properties")
            .satisfies(a -> assertThat(a.getSeveridad()).as("check severidad").isEqualTo(expected.getSeveridad()))
            .satisfies(a -> assertThat(a.getDesde()).as("check desde").isEqualTo(expected.getDesde()))
            .satisfies(a -> assertThat(a.getHasta()).as("check hasta").isEqualTo(expected.getHasta()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpactoPropagadoUpdatableRelationshipsEquals(ImpactoPropagado expected, ImpactoPropagado actual) {
        assertThat(actual)
            .as("Verify ImpactoPropagado relationships")
            .satisfies(a -> assertThat(a.getIncidente()).as("check incidente").isEqualTo(expected.getIncidente()))
            .satisfies(a -> assertThat(a.getServicio()).as("check servicio").isEqualTo(expected.getServicio()))
            .satisfies(a -> assertThat(a.getDependencia()).as("check dependencia").isEqualTo(expected.getDependencia()));
    }
}
