package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServicioCriticoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioCriticoAllPropertiesEquals(ServicioCritico expected, ServicioCritico actual) {
        assertServicioCriticoAutoGeneratedPropertiesEquals(expected, actual);
        assertServicioCriticoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioCriticoAllUpdatablePropertiesEquals(ServicioCritico expected, ServicioCritico actual) {
        assertServicioCriticoUpdatableFieldsEquals(expected, actual);
        assertServicioCriticoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioCriticoAutoGeneratedPropertiesEquals(ServicioCritico expected, ServicioCritico actual) {
        assertThat(actual)
            .as("Verify ServicioCritico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioCriticoUpdatableFieldsEquals(ServicioCritico expected, ServicioCritico actual) {
        assertThat(actual)
            .as("Verify ServicioCritico relevant properties")
            .satisfies(a -> assertThat(a.getVolvioCriticoEn()).as("check volvioCriticoEn").isEqualTo(expected.getVolvioCriticoEn()))
            .satisfies(a -> assertThat(a.getMotivo()).as("check motivo").isEqualTo(expected.getMotivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioCriticoUpdatableRelationshipsEquals(ServicioCritico expected, ServicioCritico actual) {
        assertThat(actual)
            .as("Verify ServicioCritico relationships")
            .satisfies(a -> assertThat(a.getServicio()).as("check servicio").isEqualTo(expected.getServicio()));
    }
}
